### ISSUE TITLE
Build for OpenSUSE fails

### ISSUE THREAD

**Issue by jayvdb** [open-contracting/ocds-merge#23]
At least `tests/fixtures/schema.json` and `LICENSE` are missing.

I recommend using `check-manifest` as part of release process.

**Comment by jayvdb** [comment]
It would be helpful if some of the tests ran without internet access, as distro packaging tools like rpm run in an isolated VM without network.

At the moment the test collection fails because of `schema = requests.get(url.format(patch_tag)).json()`.

If the sdist contained copies of those schema files, maybe some of the tests can be run?

**Comment by jpmckinney** [comment]
Thanks for reporting and suggesting solutions! These are now fixed in 0.5.4 https://pypi.org/project/ocdsmerge/

**Comment by jayvdb** [comment]
Great.

Now there are 79 failed and 75 passed.

Log available at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-ocdsmerge

**Comment by jayvdb** [comment]
They seem to mostly be connection errors, so more caching needed, or skips added for tests which are impossible in an isolated VM.

**Comment by jpmckinney** [comment]
Aha, the VCR cassettes were missing from the MANIFEST.in. Fixed in 0.5.5.

**Comment by jpmckinney** [comment]
Let me know if the build still fails. Closing for now.

**Comment by jayvdb** [comment]
Still 79 failed, 75 passed

**Comment by jpmckinney** [comment]
I see `Unknown pytest.mark.vcr`.

It doesn't look like you installed the [test dependencies in setup.py](https://github.com/open-contracting/ocds-merge/blob/master/setup.py#L21).

The pytest command you are running is `py.test-3.7 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v -vvv`

Try also adding `--vcr-record=none` to that command, like in [.travis.yml](https://github.com/open-contracting/ocds-merge/blob/master/.travis.yml#L13).

**Comment by jayvdb** [comment]
All green now.

However, one last thing, the setup.py is now trying to install `tests` into site-packages.  need to exclude that in setup.py `packages=...` , either explicitly list the packages, or find_packages needs an arg to exclude `tests`, and iirc, it needs something like `exclude=['tests', 'tests.*']` .

**Comment by jpmckinney** [comment]
Thank you for your patience – I'm learning new things about Python packages :) When I run `python setup.py build` in 0.5.6, the tests are now no longer included.

**Comment by jayvdb** [comment]
All good now.  https://pypistats.org/packages/ocdsmerge average stats are a bit too low atm to justify submitting in the openSUSE main package collection, but if they average >100 per month then I will try to submit it.  I'll work on the other tools which depend on this from @open-contracting and @openprocurement .  Are there any other projects which use ocdsmerge that you are aware of?

**Comment by jpmckinney** [comment]
Thank you for creating the package!

There's a report here with the projects on GitHub that use it: https://github.com/open-contracting/ocds-merge/network/dependents

I'll close the issue as it's resolved, but feel free to ask any further questions here.
