### ISSUE TITLE
ocds-merge adds `id` if not present?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-merge#6]
```
echo '{"releases":[{"ocid":"","id":"","date":"","tender":{"tenderers":[{"foo":"bar"}]}}]}' | ocdskit compile
```

Returns:

```
{"tag":["compiled"],"date":"","id":"","ocid":"","tender":{"tenderers":[{"id":0,"foo":"bar"}]}}
```

I wasn't expecting `"id"` to be added to `tenderers`. The [documentation](http://standard.open-contracting.org/latest/en/schema/merging/#whole-list-merge) states:

> Where the objects contain no top level id values, or the schema specifies the "wholeListMerge": true for the array in question, then merging should take place by treating the entire list of objects as a single value.

I'm not sure that the current code respects the "Where the objects contain no top level id values" part of that statement.

Also, in the past, ocdsmerge had `suppliers` and `tenderers` in `NOT_FLATTEN_KEYS`, though neither of those had set `"wholeListMerge": true` (unlike the other values `additionalClassifications` and `additionalIdentifiers` in `NOT_FLATTEN_KEYS`. I'm not sure why that was the case.

**Comment by jpmckinney** [comment]
Also, for whatever reason, fields get reordered, e.g.:

```
echo '{"releases":[{"ocid":"","id":"","date":"","tender":{"tenderers":[{"identifier":{},"foo":"bar"}]}}]}' | ocdskit compile
```

```
{"tag":["compiled"],"date":"","id":"","ocid":"","tender":{"tenderers":[{"id":0,"foo":"bar","identifier":{}}]}}
```

(`identifier` comes after `foo`, but was originally before `foo`.)

**Comment by kindly** [comment]
hmm this is a tricky one and as far as I know is undefined behaviour.

`tenderers` and `suppliers` both now have top level id values as they are ```organizationReference``` in 1.1 version of the schema and that is why `wholeListMerge` was removed.

I thought that section in the doc referred to the object as refereed to in the schema not each individual object in the data.  Part of the point the Org changes was to allow people to add tenderers and suppliers without having to copy the whole list. 

What surprised me is that looking in the schema that ids are not required in Organization References, when I assumed they must be.  I am going to raise this as an issue against the standard, as it makes no sense to have a reference without an entry in the parties list.

The behaviour of putting 'id' as the index in the list was a way to do merging when the data is invalid (well its not actually invalid now) and it works this way for all normal lists of objects with ids i.e awards, contracts.  With invalid data (i.e no `id` supplied) then I assumed (as its undefined) any merging behaviour would be fine and adding ids this way made sense and seemed most useful.  It is also needed to make the code work as it assumes there should be an `id`.

I think it would be fairly simple to remove the generated `id` values in the end, however, that does not answer the underlying question of what the merge behaviour actually should be when no `id` values are supplied for non WholeListMerge lists of objects.

**Comment by jpmckinney** [comment]
We can't require `id` as that would be backwards-incompatible.

However, in 2.0, we should require IDs, in which case the undefined behavior will be moot. So, I'm okay with closing this issue without defining that behavior. The documentation was perhaps a little ambiguous as to whether "top level id" referred to the schema or the data, but it makes sense for it to refer to the schema.
